const YOUTUBE_KEY = "COLLE_TA_CLE_ICI";
let currentQuery = '';

const translations = { fr: {dir:"ltr",set_title:"Paramètres",set_account_title:"1. Compte et Synchronisation",set_account_info:"Gestion du Compte",set_sync:"Synchronisation",set_devices:"Gestion des appareils",set_lang_title:"2. Langues et Région",set_lang_display:"Langue d'affichage",set_region:"Région et Fuseau horaire",set_security_title:"3. Sécurité et Confidentialité",set_2fa:"Validation en deux étapes 2FA",set_perms:"Autorisations",set_activity:"Activité et Historique",set_pref_title:"4. Préférences d'Utilisation",set_access:"Accessibilité",set_theme:"Thème",set_bar:"Position de la barre",set_save_btn:"Enregistrer",saveMsg:"✓ Paramètres enregistrés!",set_back_btn:"← Retour à l'accueil",placeholder:"Recher sur Baobab..."}, en: {dir:"ltr",set_title:"Settings",set_account_title:"1. Account & Sync",set_account_info:"Account Management",set_sync:"Synchronization",set_devices:"Device Management",set_lang_title:"2. Languages & Region",set_lang_display:"Display Language",set_region:"Region & Timezone",set_security_title:"3. Security & Privacy",set_2fa:"Two-Factor Authentication",set_perms:"Permissions",set_activity:"Activity & History",set_pref_title:"4. Usage Preferences",set_access:"Accessibility",set_theme:"Theme",set_bar:"Bar Position",set_save_btn:"Save",saveMsg:"✓ Settings saved!",set_back_btn:"← Back to Home",placeholder:"Search on Baobab..."} };

function t(k){ const lang=getSettings().uiLanguage; return translations[lang]?.[k] || translations['fr'][k]; }
function getSettings() { return { uiLanguage: localStorage.getItem('uiLanguage') || 'fr', region: localStorage.getItem('region') || 'sn', twoFA: localStorage.getItem('twoFA') === 'true', theme: localStorage.getItem('theme') || 'system', barPosition: localStorage.getItem('barPosition') || 'top', fontSize: localStorage.getItem('fontSize') || '16' } }

function openModal(title, content) { const modal = document.createElement('div'); modal.id = 'settingsModal'; modal.className = 'fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4'; modal.innerHTML = `<div class="bg-white dark:bg-gray-900 rounded-2xl p-6 w-full max-w-md"><h3 class="text-xl font-bold mb-4">${title}</h3><div class="mb-4">${content}</div><button onclick="closeModal()" class="w-full py-2 bg-blue-600 text-white rounded-lg">Fermer</button></div>`; document.body.appendChild(modal); }
function closeModal() { document.getElementById('settingsModal')?.remove(); }
function openAccount() { openModal(t('set_account_info'), `<label class="block mb-2">Email: <input type="email" class="w-full p-2 border rounded dark:bg-gray-800" value="user@baobab.com"></label>`); }
function openSync() { openModal(t('set_sync'), `<p>Sauvegarde Cloud activée</p>`); }
function openDevices() { openModal(t('set_devices'), `<p>📱 Samsung S23 - Actif</p>`); }
function openPermissions() { openModal(t('set_perms'), `<button onclick="navigator.mediaDevices.getUserMedia({audio:true})" class="w-full py-2 bg-blue-600 text-white rounded">Autoriser Micro</button>`); }
function openActivity() { openModal(t('set_activity'), `<button onclick="alert('Historique effacé')" class="w-full py-2 bg-red-500 text-white rounded">Effacer</button>`); }
function openAccessibility() { openModal(t('set_access'), `<label>Taille: <input type="range" min="12" max="24" value="${getSettings().fontSize}" oninput="document.documentElement.style.fontSize=this.value+'px'; localStorage.setItem('fontSize', this.value)"></label>`); }

function saveSettings() { localStorage.setItem('uiLanguage', document.getElementById('uiLanguage').value); localStorage.setItem('region', document.getElementById('region').value); localStorage.setItem('theme', document.getElementById('theme').value); localStorage.setItem('barPosition', document.getElementById('barPosition').value); localStorage.setItem('twoFA', document.getElementById('twoFA').checked); applyTranslations(); applyTheme(); applyBarPosition(); document.getElementById('saveMsg').classList.remove('hidden'); setTimeout(() => document.getElementById('saveMsg').classList.add('hidden'), 2000); }
function applyTranslations() { const tr = translations[getSettings().uiLanguage]; document.documentElement.lang = getSettings().uiLanguage; document.documentElement.dir = tr.dir; for(let key in tr) { if(document.getElementById(key)) document.getElementById(key).innerText = tr[key]; } if(document.getElementById('searchInput')) document.getElementById('searchInput').placeholder = tr.placeholder; }
function applyTheme() { const theme = getSettings().theme; document.documentElement.classList.toggle('dark', theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)); document.documentElement.style.fontSize = getSettings().fontSize + 'px'; }
function applyBarPosition() { const s = getSettings(); if(s.barPosition === 'bottom') { document.getElementById('topBar').classList.add('hidden'); document.getElementById('bottomBar').classList.remove('hidden'); } else { document.getElementById('topBar').classList.remove('hidden'); document.getElementById('bottomBar').classList.add('hidden'); } }
function showPage(pageId) { document.querySelectorAll('.page').forEach(p => p.classList.remove('active')); document.getElementById(pageId).classList.add('active'); window.scrollTo(0,0); }

function search(event) { if(event) event.preventDefault(); let query = document.getElementById('searchInput')?.value || document.getElementById('searchInputResults').value; if(!query) return; currentQuery = query; document.getElementById('searchInputResults').value = query; showPage('resultsPage'); document.getElementById('resultCount').innerText = `Résultats pour "${query}"`; document.getElementById('resultsList').innerHTML = `<div><a href="#" class="text-xl text-blue-700 hover:underline">${query}</a><p>baobab.com</p></div>`; }

function takePhoto() { const input = document.getElementById('fileInput'); input.accept = "image/*"; input.click(); input.onchange = (e) => { const file = e.target.files[0]; if(file) { showPage('resultsPage'); document.getElementById('resultCount').innerText = `Recherche par image: ${file.name}`; document.getElementById('resultsList').innerHTML = `<img src="${URL.createObjectURL(file)}" class="w-32 rounded-lg mb-4"><p>Images similaires...</p>`; } } }
function uploadDocument() { const input = document.getElementById('fileInput'); input.accept = ".pdf,.doc,.docx,.txt"; input.click(); input.onchange = (e) => { const file = e.target.files[0]; if(file) { showPage('resultsPage'); document.getElementById('resultCount').innerText = `Document: ${file.name}`; document.getElementById('resultsList').innerHTML = `<p>📄 ${file.name}</p>`; } }
function startVoice(iconId) { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) return alert('Voix non supportée'); const recognition = new SpeechRecognition(); recognition.lang = getSettings().uiLanguage; document.getElementById(iconId).classList.add('text-red-500'); recognition.onresult = (event) => { document.getElementById('searchInput').value = event.results[0][0].transcript; search(); }; recognition.onend = () => document.getElementById(iconId).classList.remove('text-red-500'); recognition.start(); }

document.addEventListener('DOMContentLoaded', () => { const s = getSettings(); document.getElementById('uiLanguage').value = s.uiLanguage; document.getElementById('region').value = s.region; document.getElementById('theme').value = s.theme; document.getElementById('barPosition').value = s.barPosition; document.getElementById('twoFA').checked = s.twoFA; applyTranslations(); applyTheme(); applyBarPosition(); });
